# xmodmap alt and ctrl swap is ignored by keyd
# See README.md in doftiles repo to make additional manipulations with /etc/keyd/default.conf
[slack]
alt.h = A-k
alt.j = down
alt.k = up

[telegramdesktop]
alt.h = A-j
alt.j = down
alt.k = up
