#!/usr/bin/env bash
# vim: filetype=zsh

autoload -Uz compinit && compinit
bindkey " " expand-alias # space key to expand globalalias
bindkey "^[ " magic-space # ESC space to skip expanding
bindkey -M isearch " " magic-space # normal space during searches

# aliases
alias la='ls -lah'
alias sz='source ~/.zshrc'
alias du='du -d 1 -h'
alias gp='git push origin $(git branch | grep \* | sed "s/*\s*//g")'
