#!/usr/bin/env bash
# vim: filetype=zsh

autoload -U add-zsh-hook

source ~/.zsh/.zsh_ps1
source ~/.zsh/exports
source ~/.zsh/hooks
source ~/.zsh/fzf_commands/index
source ~/.zsh/aliases

precmd() {
  eval "$PROMPT_COMMAND"
}
