#!/usr/bin/env bash
# vim: filetype=zsh

rep_dir=~/rep

alias gp='git push origin $(git branch | grep \* | sed "s/*\s*//g")'

call_alias r='fzf_cd_rep'
fzf_cd_rep() {
  dir=$(ls -ldt $rep_dir/*/*/.git $rep_dir/*/.git 2> /dev/null\
    | awk '{ print "\033[0m" $9 " \033[38;5;236m[" $6 " " $7 "]"; }'\
    | sed s/\\/\.git//g\
    | sed "s|${rep_dir}\/||g"\
    | fzf --ansi --no-sort --header="repositories list"\
    | sed "s/ \[.*//g")
  [[ ! -z "$dir" ]] && cd "$rep_dir/$dir"
}

git_branch() {
  echo $(git branch --show-current)
}

git_branch_task() {
  echo \"$(git_branch | grep -o "[A-Za-z]\+-[0-9Xx]\+") - 
}

alias gc="git commit -m $(git_branch_task)"
alias gcb='git checkout -b igor/DNA-'

call_alias c='fzf_git_checkout'
fzf_git_checkout() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m --header="checkout branch") &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

call_alias d='fzf_git_delte_branches'
fzf_git_delte_branches() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -m -d $(( 2 + $(wc -l <<< "$branches") )) --header="delete branches") &&
  git branch -D $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

call_alias l='fzf_git_log'
fzf_git_log() {
  git log \
    --graph \
    --color=always \
    --date=format:'%a, %d %b %Y' \
    --format="%ad"\
    --format="%C(auto)%h%d %s %C(black)%C(bold)%cr  %C(#303030)%an %ae %ad" "$@" |

  fzf \
    --ansi \
    --no-sort \
    --reverse \
    --tiebreak=index \
    --bind=ctrl-s:toggle-sort \
    --header="git log" \
    --height=100\
    --preview="(grep -o '[a-f0-9]\{7\}' | head -1 |
                      xargs -I % sh -c 'git show --color=always % | delta | less -R') << 'FZF-EOF'
                      {}
FZF-EOF" \
    --bind ctrl-p:toggle-preview |

    sed "s/[^a-z0-9]*\([a-z0-9]\{8\}\) .*/\1/"
}

call_alias sp='fzf_git_stash_pop'
fzf_git_stash_pop() {
  result=$(echo $(
    git stash list --format="%C(reset)%gD:%gs %C(yellow)%cr" --color=always | \
    fzf --ansi --height=100 --preview='git stash show -p $(echo {1} | sed -e s/:\.\*//) | highlight --syntax=diff -O ansi' --header="git stash pop"
  ) | sed "s/:.*//")
  [[ ! -z "$result" ]] && git stash pop $result
}

call_alias sd='fzf_git_stash_drop'
fzf_git_stash_drop() {
  local result
  result=$(echo $(
    git stash list --format="%C(reset)%gD:%gs %C(yellow)%cr" --color=always | \
    fzf --ansi --multi --preview='git stash show -p $(echo {1} | sed -e s/:\.\*//) | highlight --syntax=diff -O ansi' --header="git stash drop"
  ) | sed "s/:.*//")
  [[ ! -z "$result" ]] && git stash drop $result
}
