#!/usr/bin/env bash
# vim: filetype=zsh

# fzf default command
export FZF_DEFAULT_COMMAND='ag --hidden -g . -U --color-path "1;36"'
export FZF_DEFAULT_OPTS="
  --bind=ctrl-l:toggle
  --history=$HOME/.fzf-history
  --no-hscroll
  --color fg:242,bg:236,hl:65,fg+:15,bg+:239,hl+:108
  --color info:108,prompt:109,spinner:108,pointer:168,marker:168
  --height=10
"

autoload -Uz compinit && compinit
bindkey " " expand-alias # space key to expand globalalias
# bindkey "^[ " magic-space # ESC space to skip expanding
# TODO: figure out wtf it does bindkey -M isearch " " magic-space # normal space during searches
source ~/.zsh/aliases/alias-expand
source ~/.zsh/aliases/git
source ~/.zsh/aliases/previews
source ~/.zsh/aliases/system

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

start() {
  if [[ -f "package-lock.json" ]]; then
    npm run start
  elif [[ -f "yarn.lock" ]]; then
    yarn start
  fi
}

export FZF_COMPLETION_TRIGGER=''
bindkey '^I' expand-or-complete
