#!/usr/bin/env bash
# vim: filetype=zsh

alias la='ls -lah'
alias sz='source ~/.zshrc'
alias du='du -d 1 -h'

call_alias k='fzf_kill_process'
fzf_kill_process() {
  local pid
  pid=$(ps -ef | sed 1d | fzf -m --header="kill process" | awk '{print $2}')

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

print_alias h="fzf_history"
fzf_history() {
  cat ~/.zsh_history\
  | awk '!x[$0]++'\
  | fzf --tac --no-sort --bind=ctrl-s:toggle-sort --header="execute command from history"
}
