#!/usr/bin/env bash
# vim: filetype=zsh

# Chrome history
qalias ch='fzf_chrome_history'
alias fch='fzf_chrome_history'
fzf_chrome_history() {
  local cols sep google_history open
  cols=$(( COLUMNS / 3 ))
  sep='{::}'

  if [ "$(uname)" = "Darwin" ]; then
    google_history="$HOME/Library/Application Support/Google/Chrome/Default/History"
    open=open
  else
    google_history="$HOME/.config/google-chrome/Default/History"
    open=xdg-open
  fi
  cp -f "$google_history" /tmp/h
  sqlite3 -separator $sep /tmp/h \
    "select substr(title, 1, $cols), url
     from urls order by last_visit_time desc" |
  awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}' |
  fzf --ansi --multi --header="chrome history" | sed 's#.*\(https*://\)#\1#' | xargs $open > /dev/null 2> /dev/null
}

# Chrome bookmarks
alias cb='fzf_chrome_bookmarks'
alias fcb='fzf_chrome_bookmarks'
fzf_chrome_bookmarks() {
  ruby ~/.zsh/util/chrome_bookmarks.rb\
  | fzf --ansi --header="chrome bookmarks"\
  | awk '{print $NF}'\
  | xargs open > /dev/null 2> /dev/null
}
