#!/usr/bin/env bash
# vim: filetype=zsh

# kill process
fkill() {
  local pid
  pid=$(ps -ef | sed 1d | fzf -m | awk '{print $2}')

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

# ssh to known hosts
fs() {
  local host
  host=$(tac ~/.ssh/known_hosts | sed -e 's/ .*//' -e 's/^[^[:alpha:]]*//g' -e 's/[^[:alpha:]]*$//g' -e 's/^ *$//g' -e '/^$/d' | fzf)
  ssh $(echo ubuntu@$host)
}

# command r (search zsh_history)
alias h="fh"
fh() {
  cmd=$(cat ~/.zsh_history | sed -e 's/[^;]*;//' | uniq | fzf --tac --no-sort)
  eval $cmd
}
