#!/usr/bin/env bash
# vim: filetype=zsh

# kill process
alias k='fzf_kill_process'
alias fkill='fzf_kill_process'
fzf_kill_process() {
  local pid
  pid=$(ps -ef | sed 1d | fzf -m --header="kill process" | awk '{print $2}')

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

# command r (search zsh_history)
alias h="fzf_history"
alias fh="fzf_history"
fzf_history() {
  print -z $(\
  cat ~/.zsh_history\
  | awk '!x[$0]++'\
  | fzf --tac --no-sort --bind=ctrl-s:toggle-sort --header="execute command from history"\
  )
}
