#!/usr/bin/env bash
# vim: filetype=zsh

# cd to selected directory
alias f='fc'
fc() {
  cd $(\
  ag -g . --ignore node_modules -U\
  | sed -e 's:/[^/]*$::'\
  | uniq\
  | fzf --header="cd into directory"\
  )
}

# Find all repos in ~/rep
alias r='fr'
fr() {
  rep_dir=~/rep
  dir=$(ls -ldt $rep_dir/*/*/.git $rep_dir/*/.git 2> /dev/null\
    | awk '{ print "\033[0m" $9 " \033[38;5;236m[" $6 " " $7 "]"; }'\
    | sed s/\\/\.git//g\
    | sed "s|${rep_dir}\/||g"\
    | fzf --ansi --no-sort --header="repositories list"\
    | sed "s/ \[.*//g")
  cd "$rep_dir/$dir"
}
