#!/usr/bin/env bash
# vim: filetype=zsh

# checkout git branch
alias c='fgc'
fgc() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -d $(( 2 + $(wc -l <<< "$branches") )) +m) &&
  git checkout $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# delete branches
alias d='fgd'
fgd() {
  local branches branch
  branches=$(git for-each-ref --count=30 --sort=-committerdate refs/heads/ --format="%(refname:short)") &&
  branch=$(echo "$branches" |
           fzf-tmux -m --bind=ctrl-l:toggle -d $(( 2 + $(wc -l <<< "$branches") ))) &&
  git branch -D $(echo "$branch" | sed "s/.* //" | sed "s#remotes/[^/]*/##")
}

# git log
alias l='fgl'
fgl() {
  git log --graph --color=always \
    --format="%C(auto)%h%d %s %C(black)%C(bold)(%an) %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | delta | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}

# git log only difference with master
alias lm='fglm'
fglm() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" master.. |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}

# git stash pop
alias p='fgsp'
fgsp() {
  result=$(echo $(
    git stash list | \
    fzf --preview='git stash show -p $(echo {1} | sed -e s/:$//) | highlight --syntax=diff -O ansi'
  ) | sed "s/:.*//")
  [[ ! -z "$result" ]] && git stash pop $result
}

# git stash drop
fgsd() {
  local result
  result=$(echo $(
    git stash list |
    fzf --multi --bind=ctrl-l:toggle --preview='git stash show -p $(echo {1} | sed -e s/:$//) | highlight --syntax=diff -O ansi'
  ) | sed "s/:.*//")
  [[ ! -z "$result" ]] && git stash drop $result
}
