#!/usr/bin/env bash
# vim: filetype=zsh

# execute npm script
alias y='fzf_yarn'
alias fy='fzf_yarn'
fzf_yarn() {
  print -z "yarn" $(\
  cat package.json\
  | jq '.scripts'\
  | tail -n +2\
  | head -n +2\
  | sed "s/[\",]//g"\
  | sed "s/^ *//"\
  | fzf --header="npm scripts"\
  | sed "s/:.*//"\
  )
}

# remove dependencies
alias yu='fzf_yarn_uninstall'
alias fyuu='fzf_yarn_uninstall'
fzf_yarn_uninstall() {
  print -z "yarn uninstall" $(\
  cat package.json\
  | jq '.dependencies, .devDependencies'\
  | sed "s/[\",]//g"\
  | sed "s/^ *//"\
  | sed "s/^[\s{}]*$//"\
  | fzf --multi --header="npm scripts"\
  | sed "s/:.*//"\
  )
}
